VAR_GLOBAL
    boolean_input       AT %IX0.0 : BOOL; (* some input *)
    boolean_output      AT %QX0.0 : BOOL; (* some output *)
    byte_input          AT %IB0.0 : BOOL; (* some input *)
    byte_output         AT %QB0.0 : BOOL; (* some output *)
    uint_input          AT %IW0.0 : BOOL; (* some input *)
    uint_output         AT %QW0.0 : BOOL; (* some output *)
    udint_input         AT %ID0.0 : BOOL; (* some input *)
    udint_output        AT %QD0.0 : BOOL; (* some output *)
    ulint_input         AT %IL0.0 : BOOL; (* some input *)
    ulint_output        AT %QL0.0 : BOOL; (* some output *)
END_VAR